### ISSUE TITLE
Difficulty setting does not save

### ISSUE THREAD

**Issue by netmasa** [jweigelt/swbf2admin#18]
Hey all,

I noticed the difficulty setting is always being set to 3 (Elite), this appears to be due to the JS that runs on the page doesn't look at #game_select_difficulty so it ends up using the default property value (which is 3).

Changing web/res/game.js should be enough to fix the issue.

**Comment by jweigelt** [comment]
Yup, good catch. Fixed in e285fca8ead414678ff8445c79c9e8084452985, thank you for the detailed explanation!
