### ISSUE TITLE
Invalid space map rotation options

### ISSUE THREAD

**Issue by netmasa** [jweigelt/swbf2admin#19]
Hey all,

Slight bug due to how the code is in maps.htm, GCWAss and CWAss both have the "data-map" attribute of "g_ass". This is wrong because CWAss should have "c_ass" and should also say CW Assault.

Because of this, the invalid maps enter rotation incorrectly.

**Comment by yonilerner** [comment]
@netmasa No pressure, but just in case you werent aware, you can actually suggest these changes yourself in pull requests quite easily. eg:
- Go to https://github.com/jweigelt/swbf2admin/blob/master/DebugFiles/web/maps.htm and click the Edit button in the right corner: 
![image](https://user-images.githubusercontent.com/278810/57734878-d805c580-7657-11e9-8e0f-405eba20db0b.png)
- Make the change and select the option to create a new branch with the changes:
![image](https://user-images.githubusercontent.com/278810/57734919-ee138600-7657-11e9-9873-a190876aa4ed.png)
- Then create the pull request:
![image](https://user-images.githubusercontent.com/278810/57734973-07b4cd80-7658-11e9-9e65-4ca4c9225815.png)

And then when the repository owner is ready to approve the change, they can merge it in

**Comment by yonilerner** [comment]
Heres my PR: https://github.com/jweigelt/swbf2admin/pull/20

**Comment by yonilerner** [comment]
And thanks!

**Comment by jweigelt** [comment]
Fixed in c74786e5d4726222a52866a4179e6500bf48eaf4
