### ISSUE TITLE
Small timestamp problem

### ISSUE THREAD

**Issue by jaymanforty** [jweigelt/swbf2admin#29]
After messing with timestamps I have noticed a small problem with games starting and ending. I'm not sure the exact problem or if I'm just not reading it correctly, but it seems that some games are '30' hours long rather than the actual 25 minute timer. My theory is that maybe the time isn't being recorded until the next game starts so it stamps the same time for the end and start for either game. 

Effectively this means that if the server is unpopulated after a map and remains unpopulated for a day or two then the timestamp will get messed up and read that the one map took '30' hours or so to play. 

I was just exploring an option to find a points per minute solution that involved these timestamps recorded in the database.

**Comment by jweigelt** [comment]
The starting timestamp is created when the server finished loading the map. If the server is configured to not launch the match immediately there will therefore be a time offset. Unfortunately the game does not provide any mission timer that can be queried using the rcon interface.

**Comment by jaymanforty** [comment]
Alright, that confirms my initial train of thought. Thanks!
