### ISSUE TITLE
Can't see the server in the games server list

### ISSUE THREAD

**Issue by FatihMcFly** [jweigelt/swbf2admin#30]
I have the issue that I cannot see the server in the games server list. I have followed the instructions. I have copied the GOG files but cant see the server in Steam and GOG SWBF2. Also I dont know how to write my game directory into the cfg file. I know its opened with editor but in which format do I have to paste my game directory in? 

What am I doing wrong? I am a beginner and have no experience in this.

**Comment by jweigelt** [comment]
If you paste GameData into the ./server folder as described in README, the path setting in core.xml does not have to be changed.

Please read #24 regarding the server now showing up.

**Comment by FatihMcFly** [comment]
> If you paste GameData into the ./server folder as described in README, the path setting in core.xml does not have to be changed.
> 
> Please read #24 regarding the server now showing up.

Thank you for the quick message. I have read #24. Runtime is enabled and my GoG version is able to connect into MP aswell. I am hosting with GoG and playing with Steam and it still doesnt show up in the list. I know I am asking too much but I would be very grateful if you could connect to my PC.

**Comment by jweigelt** [comment]
Unfortunately I can't give you remote tech support, sorry. Please also provide some information regarding the setup.. (does the server window launch? is the correct network adapter selected?contents of ServerSettings.cfg, SWBF2Admin log...)
