### ISSUE TITLE
Scripts for the Server

### ISSUE THREAD

**Issue by Baadsy** [jweigelt/swbf2admin#32]
Howdy, I created with a friend an Assault Server. But now what I need are some scripts for the server like ,,Disable Force like Choke, Push and co". Is there a website for some SWBF2 scripts or must I create myself a script.

**Comment by jweigelt** [comment]
The "!applymods" command can be used to "mod .lvl files live". The command is controlled using `./cfg/mods.xml` . As recent releases required custom data files you have to update your local mods.xml file to the latest revision first:

https://raw.githubusercontent.com/jweigelt/swbf2admin/master/SWBF2Admin/Resources/cfg/mods.xml

When applying the mods, the server has to use the textureless `_LVL_PC` data that came with the original dedicated server package. (Simply copy the contents of `_LVL_PC` from the old server package to the `./server/_LVL_PC` ...) (Using textureless data files is generally a good idea for hosting servers.)

Ingame commands can then be used to apply pre-defined mods. These include (among others) a no force mod. Use `!applymods enable no_force` to disable force powers. Force can later be re-enabled using  `!applymods disable no_force`. The map has to be reloaded (for example using `!endgame`) after using `!applymods`.

**Comment by Baadsy** [comment]
Thx for the help :)
