### ISSUE TITLE
SWBF2 autokick functionality

### ISSUE THREAD

**Issue by ForceFlowingYoda** [jweigelt/swbf2admin#33]
Hello there!,

Is there a way to auto-kick for Negative score, and ban certain words for the server?

Back in the day they had those features of SWBF2 Managers, And if not, are you planning to implement them? They would be very very helpful!

Such as this https://imgur.com/a/1HKOr7w

Or could I connect this server to an old manager somehow to do that? And please go into detail if you can on how do that if possible.

Also, is there a way to have "No Force Servers. for Mos Eisley Assault" Map? And please go into detail if you can.

**Comment by jweigelt** [comment]
There is currently no autokick functionality. As there have been multiple requests, such features _might_ be implemented in the future.

Legacy server managers are currently not supported. There are also no plans to add support in the future. Just using the old manager will not work as recent game executable require extensive patching so they do not crash immediately.

Please consult #32 regarding the use of built-in modding features.

**Comment by ForceFlowingYoda** [comment]
Okay thank you very much! And Thanks for doing this project!
