### ISSUE TITLE
Multiple Servers from One Machine?

### ISSUE THREAD

**Issue by Erebusaur** [jweigelt/swbf2admin#35]
Hi Jan,

First of all, what an incredible piece of work this is. Your server manager is far easier to use than the original and more intuitive.

Secondly, I have been running a server using SWBF2 admin from a Virtual Machine. It's been running great with no issues. However, I have been trying to run a second server from the same Virtual Machine. I extracted a new copy of the files to another location and followed the instructions again, but this time I used port 8081 rather than 8080. When both servers run at the same time, there have been issues operating WebAdmin. Whichever server is launched first is the "game session" for both WebAdmins, and if I shut down the first server, it shuts down the second. There have also been some other issues, such as crashes and then the server being stuck "restarting".

Do I need to make further changes to make them both work independently? Is it even possible?

Thanks in advance. Apologies for what may have an obvious answer. I've tried to find a solution myself but I feel that I am out of my depth.

**Comment by Erebusaur** [comment]
I spoke to Michael and he suggested changing the Rcon port and the game port both to something else (e.g. 3659). This seems to have fixed the issue. I was hesitant to change that port as I don't really know how ports work, whether it it has to be 3658 or whether I can change it.

If there are any further issues, I will post it here. But otherwise you can consider this issue closed!

**Comment by jweigelt** [comment]
Hi!

As suggested, changing the second server's port is the proper way to run two servers :)
I'm closing this issue, if other problems arise feel free to just open a new issue.
