### ISSUE TITLE
Error when building project: StopEventArgs.cs & EmptyRestart.cs

### ISSUE THREAD

**Issue by cbartlett1** [jweigelt/swbf2admin#37]
Hi,

I'm trying to go about installing this incredible piece of software that you guys have made but i'm coming across some issues. 

For one, the installation guide implies the .zip comes with a SWBF2Admin.exe, but I fear I could not find one. So instead I tried to build it myself, but when trying to build I get this error:

'C:\Users\<name>\Desktop\GIT\swbf2admin\SWBF2Admin\Gameserver\StopEventArgs.cs' could not be found.

and

'C:\Users\<name>\Desktop\GIT\swbf2admin\SWBF2Admin\Runtime\Watchdog\EmptyRestart.cs' could not be found.

Any help would be appreciated, cheers :)

**Comment by SWBF2AsLan** [comment]
> 
> 
> Hi,
> 
> I'm trying to go about installing this incredible piece of software that you guys have made but i'm coming across some issues.
> 
> For one, the installation guide implies the .zip comes with a SWBF2Admin.exe, but I fear I could not find one. So instead I tried to build it myself, but when trying to build I get this error:
> 
> 'C:\Users<name>\Desktop\GIT\swbf2admin\SWBF2Admin\Gameserver\StopEventArgs.cs' could not be found.
> 
> and
> 
> 'C:\Users<name>\Desktop\GIT\swbf2admin\SWBF2Admin\Runtime\Watchdog\EmptyRestart.cs' could not be found.
> 
> Any help would be appreciated, cheers :)

If you're just wanting it to use you should download the compiled Release version here (includes the .exe): 

https://github.com/jweigelt/swbf2admin/releases/download/1.2.8/build_x86_x64.zip

It does seem like those two source files are in fact missing from github, so unless I'm missing something you won't be able to build the SWBF2Admin project yourself until they're tracked down.

**Comment by jweigelt** [comment]
The missing source files were added in 2b00c8dd19345c52ecf8fd6db23b8ff913ca39b2.
