### ISSUE TITLE
Steam Server didn't start "Assuming it has crashed"

### ISSUE THREAD

**Issue by nbrown1337** [jweigelt/swbf2admin#38]
I downloaded release 1.2.8, moved the contents of my Steam installation's GameData to ./server.
The web portal runs fine but when I try to start the server I get the following messages. 

```
5/31/2020 10:26:30 PM] INFO  | [AUDIT] admin ([::1]:49240) started the server

[5/31/2020 10:26:30 PM] INFO  | Launching server with args ''

[5/31/2020 10:26:50 PM] INFO  | Steam Launcher closed. Trying to attach to the server process.

[5/31/2020 10:27:20 PM] ERROR | Server didn't start after 31 retries. Assuming it has crashed.
```

Is it a problem that it is launching the server with no args? My core.xml config has the correct params set.

I have also set these launch parameters inside of steam: 
`/win /norender /nosound /autonet dedicated /resolution 640 480`

I should add that it seems the Steam game is crashing around the time it would be at the title screen. It has to do with the launch parameters.

Thanks for the help, would like to get dedicated without GOG version of the game.

**Comment by jweigelt** [comment]
Hosting using the Steam client is currently not supported. See #26 for details.
