### ISSUE TITLE
Accessing Webadmin from PC on same router/Don't Limit to Local Machine

### ISSUE THREAD

**Issue by ForceFlowingYoda** [jweigelt/swbf2admin#40]
Hello, I have one PC running the server, and I'm wondering how to access the WebAdmin from the same network I am running on from a separate computer. Or/and Access it from phone if that is also possible.

Currently I have it set as http://localhost:8080/ , which limits to only the computer that I am actually running the SWBF2ADMIN exe. 

"You can use either your server's IP-Address or a domain which points to your server.
    Use localhost or 127.0.0.1 to limit access to the local machine." (found in core.xml file)

What are ways to make it not limit it to my local machine? Do I have to purchase a Domain?
Can I set it to my direct IP somehow?, so that I can access it from other computers?

**Comment by jweigelt** [comment]
This section of the readme should explain how you can configure remote access:
https://github.com/jweigelt/swbf2admin#optional-allowing-remote-access-to-webadmin

To elaborate a bit more:
- Using a domain is completely optional and **not** required
- The server's local ip address can be obtained by running `ipconfig` in windows' command shell ("cmd")
- `WebAdminPrefix` always has to end with a tailing `/`

If the phone is on the same local network (for example using wifi), the web admin can be opened just like you would on a PC. If the phone is not on the same network, the web admin port has to be made accessible from WAN (using techniques like port forwarding).

**Comment by ForceFlowingYoda** [comment]
Oh okay, so do I change my webadmin access link to http://192.168.1.234:8080/ (this is the example not using my own IP)

"If you do not have a domain pointing to your server, you can also just use the server's IP-Address, for example          <WebAdminPrefix>http://192.168.1.234:8080/</WebAdminPrefix> 
but using my IP address instead of there
If you have any active firewall, the webadmin port (8080 TCP in this case) has to be unblocked."

And http://192.168.1.234:8080/ (again example link)  would be the link that works on any computer on the same router network?

Also I ran ipconfig in the cmd the one I'm looking for is the IPv4 Address?

**Comment by jweigelt** [comment]
>And http://192.168.1.234:8080/ (again example link) would be the link that works on any computer on the same router network?

>Also I ran ipconfig in the cmd the one I'm looking for is the IPv4 Address?

yes

>I tried putting in my IPv4 Address and the SWBF2Admin.exe program crashes

Please provide an error log.

**Comment by ForceFlowingYoda** [comment]
Nevermind, it worked with the IPv4 Address, I ran SWBF2Admin.exe as Administrator and it worked. Thanks for the help!
