### ISSUE TITLE
How to Add Custom Maps from Addon Folder

### ISSUE THREAD

**Issue by Shepardnick** [jweigelt/swbf2admin#41]
I'm having difficulty determining how I should go about adding modded maps from the addon folder within the server folder. The documentation refers to 'hexedit' mods, but I'm not entirely sure if they're one and the same as traditional mods. Any assistance would be appreciated.

**Comment by jweigelt** [comment]
Issue #31 should explain how to add custom maps :)

**Comment by Shepardnick** [comment]
Thank you for the reply. How about custom game types and eras?

**Comment by jweigelt** [comment]
Unfortunately custom game types/eras are not supported at this point in time.
