### ISSUE TITLE
Failed to connect to rcon server

### ISSUE THREAD

**Issue by Erebusaur** [jweigelt/swbf2admin#44]
Hi Lekeks.

We have had an error appear for several of our server. I'll post an example of it:

_[22/03/2021 00:38:45] ERROR | Failed to connect to rcon server at '192.236.161.206:3659' (System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 192.236.161.206:3659
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at SWBF2Admin.Runtime.Rcon.RconClient.Start())
[22/03/2021 00:38:45] ERROR | Failed to start runtime management (No connection could be made because the target machine actively refused it 192.236.161.206:3659)_

This error did not used to exist but in the last few months it's appeared on all but three of our servers (we have eight in total). I have tried the suggestions from the previous ticket. Runtime delay is at 3000, the rcon and gameport is the same, the ports are set up fine because this was working before (and the issue happens even with Firewall disabled). I'm at a loss, but it means webadmin is down for all of these servers.

This is the contents of the ServerSettings file for the above server:

_/gamename "[BFH] Amsterdam"
/password "XXXX"
/adminpw "XXXX" (censored)
/ip "192.236.161.206"
/gameport 3659
/rconport 3659
/tps 30
/playerlimit 9
/playercount 8
/lan 0
/bandwidth 16384
/voicemode 3
/netregion "EU"
/videostd "NTSC"
/nodroplagjumps
/nowaitlate
/nosplitupdate
/lagversion 0
/heroes 0
/hrunlock 3
/hrunlockvalue 10
/hrplayer 1
/hrteam 1
/hrrespawn 90
/contimelimit 15
/conreinforcements 200
/conaiperteam 0
/ctfscorelimit 3
/ctftimelimit 15
/ctfaiperteam 0
/huntscorelimit 0
/huntimelimit 0
/assscorelimit 0
/assreinforcements 0
/assaiperteam 0
/elitimelimit 0
/eliaiperteam 0
/shownames 1
/teamdamage 1
/awards 0
/autoassignteams 0
/difficulty 1
/spawn 2
/pregametime 0
/kickvotethreshold 0
/teamvotethreshold 0
/aimassist 0
/randomize 0
/autoannounceperiod 1_

**Comment by kingzy21** [comment]
Sounds very much like firewall issue if the connection was actively refused. Check you have port 3659 open on windows firewall and if you are planning on making it public do the same on your router.
