### ISSUE TITLE
Unable to add modded maps to server

### ISSUE THREAD

**Issue by Floofis** [jweigelt/swbf2admin#61]
None of the modded maps are showing up on the server, only the base game maps are working

**Comment by jaymanforty** [comment]
To add maps to the list in webadmin you'll have to edit the sqlite database file using something like DB browser for sqlite. 

You will add a new row for each map you want to add. 

You'll need to know the 3 letter code of the mod maps you are adding as well as the map integer. The integer is what determines which modes and eras are available for selection in webadmin. 

To calculate the integer you can use the gametype_flag_calc.htm file included in the release files.
