### ISSUE TITLE
I can't drag and drop maps???

### ISSUE THREAD

**Issue by Abro61209** [jweigelt/swbf2admin#62]
![image](https://user-images.githubusercontent.com/31665507/235028129-4670f040-349d-4bef-b675-4ce702047c96.png)

The webadmin isn't allowing me to drag and drop any maps at all. What am I missing here??

**Comment by Abro61209** [comment]
Had to add them manually through the ServerRotation.cfg, which was kind of annoying. You need to put the shortname of the map (found in the map rotation tab in SWBF2admin) and c_<gamemode> or g_<gamemode>, C for Clone Wars, G for Galactic Civil War. Rinse and repeat for all game modes. Just use whatever you see in the map rotation tab and you're all good.

This thing needs more work, but is clearly a dead project. I'm thankful it even works at all with Steam/GOG.

**Comment by Abro61209** [comment]
Drag and dropping doesn't work in Microsoft Edge. I opened the webadmins in chrome and now it works lol.

Closing this.

**Comment by IllumiC** [comment]
For future reference, ensure you drag onto the Map Rotation text, not onto the space below it.
