### ISSUE TITLE
Server fails to launch d/t "WebAdmin error"

### ISSUE THREAD

**Issue by Sintra4** [jweigelt/swbf2admin#66]
When trying to launch the server from the WebAdmin in my browser, it fails to launch and I get this notification from the interface that opens with SWBF2Admin.exe: 
"ERROR | [WEB] WebAdmin error(System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SWBF2Admin.Gameserver.ServerManager.Start()
   at SWBF2Admin.Web.Pages.DashboardPage.HandlePost(HttpListenerContext ctx, WebUser user, String postData)
   at SWBF2Admin.Web.Pages.AjaxPage.HandleContext(HttpListenerContext ctx, WebUser user)
   at SWBF2Admin.Web.WebServer.HandleContext(HttpListenerContext ctx))"

I've tried (in no particular order) uninstalling and reinstalling everything (The game through GoG Galaxy and the server software from here), I've read and followed the directions in the Readme very carefully, I've tried running the software as an Admin, I've tried using different web browsers, and I've checked my security to make sure that nothing's being blocked. It might be worth noting that I had all of this working earlier today and yesterday with the exact same setup. Everything I've tried produces the exact same error message.

**Comment by IllumiC** [comment]
I'm getting the same error, however this is my first time attempting this.
Note that the DLL / exe was not blocked for me, so I skipped the unblocking step.

**Comment by jweigelt** [comment]
Hi!

The error suggests that BattlefrontII.exe can not be found. As IllumiC noted, BattlefrontII.exe has to be in the `./server` folder, *unless* you manually modified `<ServerPath>` in `core.xml`. What build /game variant are you running?

**Comment by Sintra4** [comment]
Looks like I made the same mistake that IllumiC made. Thanks to both of you for your help.
