### ISSUE TITLE
SWBF2Admin.exe Location?

### ISSUE THREAD

**Issue by Legitosity** [jweigelt/swbf2admin#7]
I know the readme file is out of date, I feel like I'm close though I just don't know where the actual exe is located.

**Comment by jweigelt** [comment]
swbf2admin.exe can be found in the build zip attached to project releases: https://github.com/jweigelt/swbf2admin/releases

**Comment by Legitosity** [comment]
Thanks so much! Aslan told me yesterday the issue was I downloaded the source code, not the release & I forgot to mark this completed.
