### ISSUE TITLE
Cannot find GameData content

### ISSUE THREAD

**Issue by Donhomerj** [jweigelt/swbf2admin#9]
Hi, I still have issues installing it.
The readme says about 

>Copy the data folder from the dedicated server installation to your SWBF2 installation. Replace all files except shell.lvl!
> Copy the contents of the GameData folder that came with SWBF2Admin to your server's GameData folder

I cannot find the GameData folder, that came with SWBF2Admin. I still have the battlefront2.exe from steam, so the server starts, but its acting pretty weird and it does not seem to work properly

**Comment by Legitosity** [comment]
There isn't a GameData folder, those files are now located in the server folder I believe.

**Comment by jweigelt** [comment]
The updated readme in https://github.com/jweigelt/swbf2admin/commit/869ca1a95403a47371bffa31c1f779eb7cc776ec should clarify this.
